model:
  arch: vit_base
  patch_size: 8
  pre_training: dino

found:
  bkg_th: 0.18
  feats: k

training:
  dataset: ouster_images_intensity
  dataset_set: null

  # Hyper params
  seed: 0
  max_iter: 500
  nb_epochs: 6
  batch_size: 50
  lr0: 5e-2
  step_lr_size: 50
  step_lr_gamma: 0.95
  w_bs_loss: 1.5
  w_self_loss: 4.0
  stop_bkg_loss: 100

  # Augmentations
  crop_size: 64
  scale_range: [0.9, 1.1]
  photometric_aug: gaussian_blur
  proba_photometric_aug: 0.5
  cropping_strategy: random_scale

evaluation:
  type: saliency
  datasets: []
  freq: 50